services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - main-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.0
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - main-network

  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.0
    ports:
      - "5003:5003"
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    networks:
      - main-network
  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - main-network
  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
    networks:
      - main-network
  grafana:
    volumes:
      - grafana_storage:/var/lib/grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - main-network

networks:
  main-network:
    name: main-network
    external: true

volumes:
  esdata:
  grafana_storage:
