services:
  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - main-network
  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
    networks:
      - main-network
  grafana:
    volumes:
      - grafana_storage:/var/lib/grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - main-network

networks:
  main-network:
    name: main-network
    external: true

volumes:
  grafana_storage:
