services:
  s3:
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - main-network
    volumes:
      - s3-data:/data
    env_file:
      - .env.build
    environment:
      MINIO_ROOT_USER: ${DB_USER}
      MINIO_ROOT_PASSWORD: ${DB_PASSWORD}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    command: server --console-address ':9001' /data
  postgres:
    container_name: auth_service_postgres
    image: postgres:latest
    env_file:
      - .env.build
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
    networks:
      - app-network
      - main-network
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    container_name: auth_service_redis
    image: redis:latest
    env_file:
      - .env.build
    ports:
      - '6379:6379'
    networks:
      - app-network

  pgadmin:
    container_name: auth_service_pgadmin
    image: dpage/pgadmin4
    env_file:
      - '.env.build'
    environment:
      PGADMIN_DEFAULT_EMAIL: 'timar@timar.com'
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - '5050:80'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 600M
    networks:
      - app-network

volumes:
  pgdata:
  pgadmin-data:
  s3-data:

networks:
  app-network:
    name: auth_service_app-network
    driver: bridge
  main-network:
    external: true
